### ISSUE TITLE
fragments not rendered 

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#65] opened 2015-05-04 22:05 UTC
This is, for example, about a page like this:

http://101companies.org/wiki/Local_scope

The page contains markup like this:

![image](https://cloud.githubusercontent.com/assets/1208815/7463524/61a90746-f2ba-11e4-8026-c96fc9e93bf5.png)

It is rendered in a way that the underlying source code does not show up:

![image](https://cloud.githubusercontent.com/assets/1208815/7463453/ca9aaff8-f2b9-11e4-8163-1991e2d9f247.png)

**Comment by kevin-klein** [comment] 2015-05-05 11:58
Caused by: https://github.com/101companies/101worker/issues/189

**Comment by rlaemmel** [comment] 2015-05-12 19:25
@martinleinberger @hartenfels @kevin-klein 

Please help.

This is probably the same as https://github.com/101companies/101worker/issues/192

Several pages look very broken because of this. This is a severe issue for the course.

**Comment by martinleinberger** [comment] 2015-06-08 15:34
Not yet fixed

**Comment by lukasschmelzeisen** [comment] 2015-06-29 08:47
Seems fixed now with https://github.com/101companies/101worker/commit/8dc394aa844d54ff9b3be1e1d649ab4bdc962135, so this and https://github.com/101companies/101worker/issues/192 can be closed?

**Comment by kevin-klein** [comment] 2015-06-29 11:04
I think we made the Local scope site work earlier, @martinleinberger can you give an example of which site broke?

**Comment by kevin-klein** [comment] 2015-09-23 14:55
Seems fixed for quite some time

**Closed by kevin-klein** 2015-09-23 14:55 UTC
Labels: bug
