### ISSUE TITLE
The return of the dreadful doubles

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101rails#113] opened 2016-02-03 20:41 UTC
![image](https://cloud.githubusercontent.com/assets/1208815/12796416/e31a497a-cabe-11e5-96e3-907f39ec5d7d.png)

**Comment by rlaemmel** [comment] 2016-02-17 13:53
cc @kevin-klein 
This continues to trouble us.
![image](https://cloud.githubusercontent.com/assets/1208815/13111449/27f3ea8e-d586-11e5-835f-99f2432783b4.png)

**Comment by kevin-klein** [comment] 2016-02-17 23:31
There are extensive tests to find this sort of behaviour but i have not been able to replicate this in any test so far. But the structure of the data suggests a pretty specific point in the page creation process as the source of the error, just i have no explanation about why the page is saved too early and resulting in those "concept" results. I think the best solution is to remove the Page#prepare_the_page callback (https://github.com/101companies/101rails/blob/master/app/models/page.rb#L53) and rework the process for page rendering.

**Comment by rlaemmel** [comment] 2016-02-25 15:26
a) the doubles are still there
b) Just renamed "Ghost Field" to "Ghost field". Now both seem to be there

![image](https://cloud.githubusercontent.com/assets/1208815/13324070/78027926-dbdc-11e5-9ab7-aea08f489242.png)

**Comment by rlaemmel** [comment] 2016-04-13 19:52
The doubles are still there it seems :-(

![image](https://cloud.githubusercontent.com/assets/1208815/14507237/02a66370-01c2-11e6-987c-4c0a800034e8.png)

**Comment by rlaemmel** [comment] 2016-04-22 07:10
There are many, many cases of pages that exist also without namespaces.

![image](https://cloud.githubusercontent.com/assets/1208815/14734333/01fb9bd0-086a-11e6-8f81-f0576d13c339.png)

**Comment by kevin-klein** [comment] 2016-04-22 09:46
I am fairly certain that it is just a matter of cleanup, all doubles you identified were created mid-december last year.

**Comment by rlaemmel** [comment] 2016-04-22 10:15
As there are so many doubles, that clean-up would need to be somehow automated.
We can talk about this on Monday, if you need my input.

Regards,
Ralf

**Comment by kevin-klein** [comment] 2016-04-22 10:16
I ran a more aggressive version of the program i used before. Actually like 20 minutes ago. So done but there is a backup in case i screwed something up.

**Comment by rlaemmel** [comment] 2016-05-23 20:46
We do have still problems like this:

![image](https://cloud.githubusercontent.com/assets/1208815/15484027/2c22e47c-2138-11e6-9678-345c0a01f3c7.png)

cc @MarcelH91

**Comment by kevin-klein** [comment] 2016-11-14 17:27
duplicate of #143

**Closed by kevin-klein** 2016-11-14 17:27 UTC
Labels: bug, duplicate
